/**
 * Product Naming Utility
 * Produces clean, title-cased, professional product names from Color + Product Type.
 */

/**
 * Converts stored color name (often UPPERCASE) to clean Title Case.
 * e.g., 'JET BLACK' -> 'Jet Black'
 *       '5% MELANGE' -> '5% Melange'
 *       'BABY PINK'  -> 'Baby Pink'
 *       'MEHRON'     -> 'Mehron'
 */
export function formatColorTitleCase(colorName?: string | null): string {
  if (!colorName || typeof colorName !== 'string') return '';
  const trimmed = colorName.trim();
  if (!trimmed) return '';

  return trimmed
    .split(/\s+/)
    .map(word => {
      // Preserve percentage prefix like 5% or 15%
      if (/^\d+%/.test(word)) {
        const rest = word.replace(/^\d+%/, '');
        if (!rest) return word;
        return word.slice(0, word.indexOf('%') + 1) + rest.charAt(0).toUpperCase() + rest.slice(1).toLowerCase();
      }
      // Standard title casing
      return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
    })
    .join(' ');
}

/**
 * Auto-generates standard Product Name:
 * Format: COLOR + PRODUCT TYPE
 * e.g., 'Baby Pink' + 'Zipper Polo T-Shirt' -> 'Baby Pink Zipper Polo T-Shirt'
 */
export function generateProductName(colorName?: string | null, productTypeName?: string | null): string {
  const formattedColor = formatColorTitleCase(colorName);
  const formattedType = (productTypeName || '').trim();

  if (formattedColor && formattedType) {
    return `${formattedColor} ${formattedType}`;
  }
  if (formattedType) {
    return formattedType;
  }
  if (formattedColor) {
    return formattedColor;
  }
  return '';
}

/**
 * Checks if a given product name matches the automatically generated name pattern
 * for the current color & product type selection.
 */
export function matchesAutoGeneratedName(
  currentName: string,
  colorName?: string | null,
  productTypeName?: string | null
): boolean {
  if (!currentName || !currentName.trim()) return true;
  const expected = generateProductName(colorName, productTypeName);
  return currentName.trim().toLowerCase() === expected.trim().toLowerCase();
}

/**
 * Generates an intelligent, high-converting product description based on garment attributes.
 */
export function generateProductDescription(params: {
  colorName?: string | null;
  productTypeName?: string | null;
  categoryName?: string | null;
}): string {
  const color = formatColorTitleCase(params.colorName) || 'Premium';
  const type = (params.productTypeName || 'Polo T-Shirt').trim();
  const typeLower = type.toLowerCase();
  const catLower = (params.categoryName || '').toLowerCase();

  if (typeLower.includes('zipper polo') || typeLower.includes('zip polo')) {
    return `Add a refined touch to your everyday wardrobe with our ${color} ${type}. Designed in a versatile polo silhouette with a convenient front zipper, this style offers a clean, contemporary look with comfortable everyday wearability.`;
  }

  if (typeLower.includes('button polo') || typeLower.includes('polo')) {
    return `Elevate your smart-casual rotation with our ${color} ${type}. Crafted from breathable, high-grade knit fabric, it features a structured collar and tailored silhouette for all-day comfort and timeless appeal.`;
  }

  if (typeLower.includes('oversized')) {
    return `Step up your streetwear aesthetic with our ${color} ${type}. Cut with a relaxed, dropped-shoulder silhouette in premium heavyweight cotton, delivering effortless style and breathable comfort.`;
  }

  if (typeLower.includes('henley')) {
    return `A timeless classic with modern edge, our ${color} ${type} features a signature button placket and flattering cut, perfect for effortless layering or standalone styling.`;
  }

  if (typeLower.includes('hoodie') || typeLower.includes('sweatshirt') || catLower.includes('hoodie')) {
    return `Stay cozy in style with our ${color} ${type}. Tailored from plush, warm fabric with snug ribbed trims, perfect for brisk weather and casual weekend layering.`;
  }

  if (typeLower.includes('jacket') || catLower.includes('jacket')) {
    return `Upgrade your outerwear with our ${color} ${type}. Engineered for crisp structure, lightweight warmth, and reliable durability across seasons.`;
  }

  if (typeLower.includes('pant') || typeLower.includes('jean') || typeLower.includes('trouser') || catLower.includes('jean') || catLower.includes('pant')) {
    return `Designed for all-day versatility, our ${color} ${type} combines modern tailoring with flexible movement. Features durable construction and a sleek silhouette suitable for work or weekend wear.`;
  }

  return `Add a refined touch to your everyday wardrobe with our ${color} ${type}. Crafted with precision from premium quality fabric to deliver lasting comfort, durability, and a polished contemporary look.`;
}

export const DEFAULT_WASH_CARE = 'Cold and gentle machine wash. Do not bleach. Do not iron directly on metal zipper.';
export const DEFAULT_FREE_SHIPPING = 'Free shipping across India on all prepaid & COD orders.';
export const DEFAULT_DELIVERY_HEADING = '2–5 Days Delivery';
export const DEFAULT_DELIVERY_CONTENT = `Dispatch: All orders are dispatched within 1–2 business days from our warehouse.\n\nDelivery: Metros: 2–3 business days. Rest of India: 3–5 business days.`;
export const DEFAULT_RETURNS_HEADING = '7 Days Returns & Exchange';
export const DEFAULT_RETURNS_CONTENT = 'Eligible for exchange or return within 7 days of delivery.';

