"use client";

import { useState, useRef, useMemo, useEffect } from 'react';
import Link from 'next/link';
import { useSearchParams, useRouter } from 'next/navigation';
import Portal from '@/components/Portal';
import { 
  Plus, 
  Edit, 
  Trash2, 
  UploadCloud, 
  ArrowLeft, 
  Save,
  Check, 
  Copy, 
  RefreshCw, 
  Search, 
  Package, 
  AlertTriangle, 
  ChevronDown, 
  Eye, 
  EyeOff, 
  FileText,
  Truck,
  RotateCcw,
  Percent,
  Star,
  ArrowLeftRight,
  ChevronLeft,
  ChevronRight
} from 'lucide-react';
import formStyles from './product-form.module.css';
import { deleteProduct } from '../../../actions/products';
import { createColor } from '../../../actions/config';
import { calculateDiscountPercentage, validatePricing, getProductPricing } from '@/lib/pricing';
import { 
  generateProductName, 
  formatColorTitleCase, 
  matchesAutoGeneratedName,
  generateProductDescription,
  DEFAULT_WASH_CARE,
  DEFAULT_FREE_SHIPPING,
  DEFAULT_DELIVERY_HEADING,
  DEFAULT_DELIVERY_CONTENT,
  DEFAULT_RETURNS_HEADING,
  DEFAULT_RETURNS_CONTENT
} from '@/lib/productNaming';
import { 
  buildSkuPrefix, 
  buildVariantSku, 
  generateDeterministicSku, 
  resolveCategoryCode, 
  resolveColorCode, 
  resolveProductTypeCode,
  normalizeConfigPart
} from '@/lib/sku';
import { 
  INITIAL_PREDEFINED_COLORS, 
  HOODIE_COLORS,
  INITIAL_CATEGORIES, 
  INITIAL_PRODUCT_TYPES, 
  INITIAL_HOODIE_PRODUCT_TYPES,
  INITIAL_TSHIRT_PRODUCT_TYPES,
  INITIAL_GARMENT_SIZES,
  isHoodieCategory,
  isTShirtCategory,
  getCategoryProductTypes,
  getCategoryColors,
  DEFAULT_HOODIE_MRP,
  DEFAULT_HOODIE_SELLING_PRICE,
  DEFAULT_STANDARD_MRP,
  DEFAULT_STANDARD_SELLING_PRICE
} from '@/lib/catalogueDefaults';

interface ProductImageItem {
  id?: string;
  url: string;
  publicId?: string;
  altText: string;
  isPrimary: boolean;
  sortOrder: number;
}

const ALL_SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', '4XL', '5XL', 'Free Size'];

export default function ProductsClient({ 
  initialProducts, 
  categories,
  initialColors = [],
  initialSizes = []
}: { 
  initialProducts: any[]; 
  categories: any[]; 
  initialColors?: any[];
  initialSizes?: any[];
}) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [products, setProducts] = useState(initialProducts);

  useEffect(() => {
    if (initialProducts && initialProducts.length > 0) {
      setProducts(initialProducts);
    } else {
      fetch('/api/admin/products')
        .then(res => res.json())
        .then(data => {
          if (data && data.products && data.products.length > 0) {
            setProducts(data.products);
          }
        })
        .catch(() => {});
    }
  }, [initialProducts]);
  
  // View mode
  const [isEditing, setIsEditing] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  
  const [error, setError] = useState('');
  const [successToast, setSuccessToast] = useState('');
  const [loading, setLoading] = useState(false);
  const [isUploadingImages, setIsUploadingImages] = useState(false);
  const [statusUpdatingId, setStatusUpdatingId] = useState<string | null>(null);
  const [copiedSku, setCopiedSku] = useState<string | null>(null);
  
  // Deletion Modal State
  const [productToDelete, setProductToDelete] = useState<any | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Available Custom Colors Library (added via "+ Add Custom Color")
  const [customColors, setCustomColors] = useState<any[]>([]);

  // T-Shirt color palette (17 classic colors + any custom colors)
  const tshirtColors = useMemo(() => {
    const list: any[] = initialColors.length > 0 ? [...initialColors] : [...INITIAL_PREDEFINED_COLORS];
    INITIAL_PREDEFINED_COLORS.forEach(initCol => {
      if (!list.some(c => c.name.toUpperCase() === initCol.name.toUpperCase())) {
        list.push(initCol);
      }
    });
    const tshirtAllowed = new Set(INITIAL_PREDEFINED_COLORS.map(c => c.name.toUpperCase()).concat(['RAMA GREEN']));
    const filtered = list.filter(c => tshirtAllowed.has(c.name.toUpperCase()) || c.isCustom);
    customColors.forEach(cc => {
      if (!filtered.some(c => c.name.toUpperCase() === cc.name.toUpperCase())) {
        filtered.push(cc);
      }
    });
    return filtered;
  }, [initialColors, customColors]);

  // Hoodie color palette (strictly the 18 Hoodie colors + any custom colors)
  const hoodieColors = useMemo(() => {
    const list: any[] = [...HOODIE_COLORS];
    customColors.forEach(cc => {
      if (!list.some(c => c.name.toUpperCase() === cc.name.toUpperCase())) {
        list.push(cc);
      }
    });
    return list;
  }, [customColors]);

  const [customColorInput, setCustomColorInput] = useState('');

  // Search & Filter State for Product List Table
  const [searchQuery, setSearchQuery] = useState('');
  const [categoryFilter, setCategoryFilter] = useState('ALL');
  const [statusFilter, setStatusFilter] = useState('ALL');

  // ==========================================================================
  // FORM STATE
  // ==========================================================================
  // 1. Category & Product Type - Default to empty/unselected
  const [categoryId, setCategoryId] = useState('');
  const currentCategory = useMemo(() => {
    if (!categoryId) return null;
    return categories.find(c => c.id === categoryId) || null;
  }, [categories, categoryId]);

  // Dynamically selected colors list strictly according to active Category
  const activeCategoryColors = useMemo(() => {
    if (!currentCategory) {
      return [];
    }
    if (isHoodieCategory(currentCategory)) {
      return hoodieColors;
    }
    return tshirtColors;
  }, [currentCategory, hoodieColors, tshirtColors]);

  const availableProductTypes = useMemo(() => {
    if (!currentCategory) {
      return [];
    }
    if (isHoodieCategory(currentCategory)) {
      return INITIAL_HOODIE_PRODUCT_TYPES;
    }
    if (isTShirtCategory(currentCategory)) {
      if (currentCategory?.productTypes && currentCategory.productTypes.length > 0) {
        const filtered = currentCategory.productTypes.filter((pt: any) =>
          INITIAL_TSHIRT_PRODUCT_TYPES.some(tt => tt.name.toLowerCase() === pt.name.toLowerCase())
        );
        if (filtered.length > 0) return filtered;
      }
      return INITIAL_TSHIRT_PRODUCT_TYPES;
    }
    if (currentCategory?.productTypes && currentCategory.productTypes.length > 0) {
      return currentCategory.productTypes;
    }
    return getCategoryProductTypes(currentCategory);
  }, [currentCategory]);

  const [productType, setProductType] = useState('');

  // Clear productType if it becomes invalid in the new category; do NOT auto-select
  useEffect(() => {
    if (productType && availableProductTypes.length > 0) {
      const hasCurrent = availableProductTypes.some((pt: any) => pt.name.toLowerCase() === productType.toLowerCase());
      if (!hasCurrent) {
        setProductType('');
      }
    } else if (availableProductTypes.length === 0 && productType) {
      setProductType('');
    }
  }, [availableProductTypes, productType]);

  // 2. Product Color, Name & SKU - Default to empty/unselected
  const [primaryColor, setPrimaryColor] = useState('');

  // Clear primaryColor if it becomes invalid in the new category; do NOT auto-select
  useEffect(() => {
    if (primaryColor && activeCategoryColors.length > 0) {
      const hasCurrent = activeCategoryColors.some((c: any) => c.name.toUpperCase() === primaryColor.toUpperCase());
      if (!hasCurrent) {
        setPrimaryColor('');
      }
    } else if (activeCategoryColors.length === 0 && primaryColor) {
      setPrimaryColor('');
    }
  }, [activeCategoryColors, primaryColor]);

  const [name, setName] = useState('');
  const [isNameManuallyEdited, setIsNameManuallyEdited] = useState(false);
  const [slug, setSlug] = useState('');

  // Strictly deterministic SKU identity based on Category + Color + Product Type
  const [sku, setSku] = useState('');

  // Track initial configuration when opening Edit Product to determine if config was altered
  const [initialConfig, setInitialConfig] = useState<{
    categoryId: string;
    productType: string;
    color: string;
    sku: string;
  } | null>(null);

  // Request sequence counter for async duplicate check to prevent race conditions
  const duplicateCheckSeqRef = useRef<number>(0);

  // Duplicate Configuration Conflict State (Stores validatedKey to eliminate stale duplicate warnings)
  const [duplicateConflict, setDuplicateConflict] = useState<{
    exists: boolean;
    validatedKey: string;
    existingProduct?: {
      id: string;
      name: string;
      sku: string;
      category?: string;
      categoryName?: string;
      productType?: string;
      color?: string;
    };
    message?: string;
  } | null>(null);
  const [isCheckingDuplicate, setIsCheckingDuplicate] = useState(false);

  // Current normalized configuration key: `${categoryId}:${normalizedProductType}:${normalizedColor}`
  const currentConfigKey = useMemo(() => {
    if (!categoryId || !productType || !primaryColor) return '';
    return `${categoryId}:${normalizeConfigPart(productType)}:${normalizeConfigPart(primaryColor)}`;
  }, [categoryId, productType, primaryColor]);

  // Evaluates to true ONLY if the conflict belongs to the CURRENTLY selected configuration
  const isCurrentDuplicate = useMemo(() => {
    if (!categoryId || !productType || !primaryColor) return false;
    if (!duplicateConflict?.exists) return false;
    return duplicateConflict.validatedKey === currentConfigKey;
  }, [categoryId, productType, primaryColor, duplicateConflict, currentConfigKey]);

  // 3. Available Sizes
  const [selectedSizes, setSelectedSizes] = useState<string[]>(['S', 'M', 'L', 'XL', 'XXL']);

  // 4. Product Images
  const [images, setImages] = useState<ProductImageItem[]>([]);

  // 5. Pricing & Discounts
  const [price, setPrice] = useState(DEFAULT_STANDARD_SELLING_PRICE);
  const [originalPrice, setOriginalPrice] = useState(DEFAULT_STANDARD_MRP);
  const [isPriceManuallyEdited, setIsPriceManuallyEdited] = useState(false);

  const calculatedDiscount = useMemo(() => {
    return calculateDiscountPercentage(originalPrice, price);
  }, [originalPrice, price]);

  const calculatedSavings = useMemo(() => {
    const orig = parseFloat(originalPrice) || 0;
    const sell = parseFloat(price) || 0;
    return orig > sell ? orig - sell : 0;
  }, [originalPrice, price]);

  const pricingValidationError = useMemo(() => {
    if (!originalPrice || !price) return null;
    const numMrp = parseFloat(originalPrice);
    const numSelling = parseFloat(price);
    if (isNaN(numMrp) || isNaN(numSelling)) return null;
    if (numSelling > numMrp) {
      return `Selling Price (₹${numSelling.toLocaleString('en-IN')}) cannot be greater than Original Price / MRP (₹${numMrp.toLocaleString('en-IN')}).`;
    }
    return null;
  }, [originalPrice, price]);

  // 6. Description & Policies
  const [description, setDescription] = useState('');
  const [isDescManuallyEdited, setIsDescManuallyEdited] = useState(false);

  const [washCare, setWashCare] = useState(DEFAULT_WASH_CARE);
  const [freeShippingText, setFreeShippingText] = useState(DEFAULT_FREE_SHIPPING);
  const [deliveryHeading, setDeliveryHeading] = useState(DEFAULT_DELIVERY_HEADING);
  const [deliveryText, setDeliveryText] = useState(DEFAULT_DELIVERY_CONTENT);
  const [returnsHeading, setReturnsHeading] = useState(DEFAULT_RETURNS_HEADING);
  const [returnPolicyText, setReturnPolicyText] = useState(DEFAULT_RETURNS_CONTENT);

  // 7. Product Status & Badges
  const [status, setStatus] = useState<'ACTIVE' | 'INACTIVE'>('ACTIVE');
  const [featured, setFeatured] = useState(false);
  const [newArrival, setNewArrival] = useState(false);
  const [showSizeChart, setShowSizeChart] = useState(true);
  const [sizeFit, setSizeFit] = useState('Tailored slim fit silhouette.');

  // Check URL query for action=add
  useEffect(() => {
    if (searchParams.get('action') === 'add') {
      handleOpenCreate();
      if (typeof window !== 'undefined' && window.history) {
        window.history.replaceState(null, '', '/admin/products');
      }
    }
  }, [searchParams]);

  // 9-Step Stepper Definition (Inventory step removed completely)
  const steps = useMemo(() => {
    return [
      { id: 'step-1', num: '1', title: 'Category', subtitle: 'Choose Category', isDone: Boolean(categoryId) },
      { id: 'step-2', num: '2', title: 'Product Type', subtitle: 'Choose Type', isDone: Boolean(productType) },
      { id: 'step-3', num: '3', title: 'Color', subtitle: 'Choose Color', isDone: Boolean(primaryColor) },
      { id: 'step-4', num: '4', title: 'Information', subtitle: 'Product Information', isDone: Boolean(name && sku) },
      { id: 'step-5', num: '5', title: 'Pricing', subtitle: 'Set Pricing', isDone: Boolean(price && originalPrice) },
      { id: 'step-6', num: '6', title: 'Sizes', subtitle: 'Select Sizes', isDone: selectedSizes.length > 0 },
      { id: 'step-7', num: '7', title: 'Images', subtitle: 'Upload Product Images', isDone: images.length > 0 },
      { id: 'step-8', num: '8', title: 'Details', subtitle: 'Description & Policies', isDone: Boolean(description) },
      { id: 'step-9', num: '9', title: 'Status', subtitle: 'Publish Product', isDone: true }
    ];
  }, [categoryId, productType, primaryColor, name, sku, price, originalPrice, selectedSizes.length, images.length, description]);

  const scrollToStep = (stepId: string) => {
    const el = document.getElementById(stepId);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  };

  // Check if current selection is the same as the original configuration in Edit mode
  const isSameAsInitialConfig = useMemo(() => {
    if (!isEditing || !editingId || !initialConfig) return false;
    const isCatSame = initialConfig.categoryId === categoryId;
    const isTypeSame = normalizeConfigPart(initialConfig.productType) === normalizeConfigPart(productType);
    const isColorSame = normalizeConfigPart(initialConfig.color) === normalizeConfigPart(primaryColor);
    return isCatSame && isTypeSame && isColorSame;
  }, [isEditing, editingId, initialConfig, categoryId, productType, primaryColor]);

  // Compute deterministic SKU based on current Category + Product Type + Color
  const currentDeterministicSku = useMemo(() => {
    if (!currentCategory || !primaryColor || !productType) {
      return '';
    }
    const categoryName = currentCategory?.name || '';
    const catCode = resolveCategoryCode(categoryName, currentCategory?.code);
    const colCode = resolveColorCode(primaryColor);
    const typCode = resolveProductTypeCode(productType);
    return `${catCode}-${colCode}-${typCode}`;
  }, [currentCategory, primaryColor, productType]);

  // Strictly Deterministic SKU Auto-Sync (CATEGORY + COLOR + TYPE)
  // Whenever Category, Product Type, or Color changes, SKU must immediately update!
  useEffect(() => {
    if (isSameAsInitialConfig && initialConfig?.sku) {
      setSku(initialConfig.sku);
    } else {
      setSku(currentDeterministicSku);
    }
  }, [isSameAsInitialConfig, initialConfig, currentDeterministicSku]);

  // Smart Auto-Sync: Name & Description
  // Whenever Color or Product Type changes, Name auto-updates to stay synchronized
  useEffect(() => {
    if (!isEditing || !editingId) {
      if (primaryColor && productType && categoryId) {
        if (!isNameManuallyEdited) {
          const autoName = generateProductName(primaryColor, productType);
          setName(autoName);
          setSlug(autoName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, ''));
        }
        if (!isDescManuallyEdited) {
          setDescription(generateProductDescription({
            colorName: primaryColor,
            productTypeName: productType,
            categoryName: currentCategory?.name
          }));
        }
      } else {
        if (!isNameManuallyEdited) {
          setName('');
          setSlug('');
        }
        if (!isDescManuallyEdited) {
          setDescription('');
        }
      }
    } else if (isEditing && editingId && !isSameAsInitialConfig) {
      // In edit mode: if config was changed, synchronize name unless user explicitly edited it
      if (primaryColor && productType && categoryId) {
        if (!isNameManuallyEdited) {
          const autoName = generateProductName(primaryColor, productType);
          setName(autoName);
          setSlug(autoName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, ''));
        }
      }
    }
  }, [primaryColor, productType, categoryId, currentCategory, isNameManuallyEdited, isDescManuallyEdited, isEditing, editingId, isSameAsInitialConfig]);

  // Instant Duplicate Detection on Category + Product Type + Color changes
  useEffect(() => {
    // 1. Immediately clear any previous duplicate state and error whenever configuration changes
    setDuplicateConflict(null);
    setError('');

    if (!categoryId || !productType || !primaryColor) {
      return;
    }

    // 2. If editing an existing product and current selection is its own unchanged configuration:
    // It is NEVER a duplicate of itself!
    if (isSameAsInitialConfig) {
      return;
    }

    const currentCat = categories.find(c => c.id === categoryId);
    const catName = currentCat?.name || '';
    const normType = normalizeConfigPart(productType);
    const normColor = normalizeConfigPart(primaryColor);
    const expectedSku = currentDeterministicSku;
    const validatedKey = `${categoryId}:${normType}:${normColor}`;

    // 3. Fast local detection against loaded products in state
    const localMatch = products.find(p => {
      if (isEditing && p.id === editingId) return false;
      const pCatMatch = p.categoryId === categoryId || 
        (p.category?.name && p.category.name.toLowerCase() === catName.toLowerCase());
      const pTypeMatch = normalizeConfigPart(p.productType) === normType;
      const pColorMatch = normalizeConfigPart(p.color) === normColor;
      const pSkuMatch = Boolean(p.sku && p.sku.toUpperCase() === expectedSku.toUpperCase());
      return (pCatMatch && pTypeMatch && pColorMatch) || pSkuMatch;
    });

    if (localMatch) {
      setDuplicateConflict({
        exists: true,
        validatedKey,
        existingProduct: {
          id: localMatch.id,
          name: localMatch.name,
          sku: localMatch.sku,
          category: localMatch.category?.name || catName,
          categoryName: localMatch.category?.name || catName,
          productType: localMatch.productType || productType,
          color: localMatch.color || primaryColor
        },
        message: 'This product configuration is already registered.'
      });
      return;
    }

    // 4. Debounced remote verification with server check-duplicate API
    // Uses AbortController and request sequence counter to prevent race conditions
    const reqSeq = ++duplicateCheckSeqRef.current;
    const controller = new AbortController();

    const timer = setTimeout(async () => {
      try {
        setIsCheckingDuplicate(true);
        const queryParams = new URLSearchParams({
          categoryId,
          categoryName: catName,
          productType,
          color: primaryColor,
          excludeProductId: (isEditing && editingId) ? editingId : '',
          excludeId: (isEditing && editingId) ? editingId : ''
        });

        const res = await fetch(`/api/admin/products/check-duplicate?${queryParams.toString()}`, {
          signal: controller.signal
        });
        
        // Ignore stale response if a newer selection occurred while fetch was in flight
        if (reqSeq !== duplicateCheckSeqRef.current) return;
        if (!res.ok) return;
        const data = await res.json();
        
        // Ignore stale response
        if (reqSeq !== duplicateCheckSeqRef.current) return;

        if (data.exists && (data.product || data.existingProduct)) {
          const match = data.product || data.existingProduct;
          setDuplicateConflict({
            exists: true,
            validatedKey,
            existingProduct: {
              id: match.id,
              name: match.name,
              sku: match.sku,
              category: match.categoryName || catName,
              categoryName: match.categoryName || catName,
              productType: match.productType || productType,
              color: match.color || primaryColor
            },
            message: data.message || 'This product configuration is already registered.'
          });
        } else {
          setDuplicateConflict(null);
        }
      } catch (err: any) {
        if (err.name !== 'AbortError') {
          console.error('Failed to verify product configuration uniqueness:', err);
        }
      } finally {
        if (reqSeq === duplicateCheckSeqRef.current) {
          setIsCheckingDuplicate(false);
        }
      }
    }, 180);

    return () => {
      clearTimeout(timer);
      controller.abort();
    };
  }, [categoryId, productType, primaryColor, categories, products, isEditing, editingId, isSameAsInitialConfig, currentDeterministicSku]);

  const handleNameChange = (newName: string) => {
    setName(newName);
    setSlug(newName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, ''));
    const isAuto = matchesAutoGeneratedName(newName, primaryColor, productType);
    setIsNameManuallyEdited(!isAuto);
  };

  const handleRegenerateName = () => {
    const autoName = generateProductName(primaryColor, productType);
    setName(autoName);
    setSlug(autoName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, ''));
    setIsNameManuallyEdited(false);
  };

  const handleRegenerateDescription = () => {
    const autoDesc = generateProductDescription({
      colorName: primaryColor,
      productTypeName: productType,
      categoryName: currentCategory?.name
    });
    setDescription(autoDesc);
    setIsDescManuallyEdited(false);
  };

  const handleCopySku = (skuText: string) => {
    if (!skuText) return;
    navigator.clipboard.writeText(skuText);
    setCopiedSku(skuText);
    setTimeout(() => setCopiedSku(null), 2000);
  };

  // Category Change Handler (Immediate state reset, category-aware types and colors)
  const handleCategoryChange = (newCatId: string) => {
    setDuplicateConflict(null);
    setError('');

    const prevCat = categories.find(c => c.id === categoryId);
    const isOldHoodie = isHoodieCategory(prevCat);

    setCategoryId(newCatId);

    if (!newCatId) {
      setProductType('');
      setPrimaryColor('');
      setSku('');
      if (!isNameManuallyEdited) {
        setName('');
        setSlug('');
      }
      if (!isDescManuallyEdited) {
        setDescription('');
      }
      if (isOldHoodie || originalPrice === DEFAULT_HOODIE_MRP) {
        setOriginalPrice(DEFAULT_STANDARD_MRP);
        setPrice(DEFAULT_STANDARD_SELLING_PRICE);
        setIsPriceManuallyEdited(false);
      }
      return;
    }

    const newCat = categories.find(c => c.id === newCatId);
    const isNewHoodie = isHoodieCategory(newCat);

    // Pricing & Discount logic for Category:
    if (isNewHoodie) {
      // Specifically for HOODIES: Original Price (MRP): ₹3,999, Selling Price: ₹1,999
      setOriginalPrice(DEFAULT_HOODIE_MRP);
      setPrice(DEFAULT_HOODIE_SELLING_PRICE);
      setIsPriceManuallyEdited(false);
    } else if (isOldHoodie || originalPrice === DEFAULT_HOODIE_MRP || !isPriceManuallyEdited) {
      // If category is changed from Hoodies to another category, do not carry the Hoodie pricing into the new category.
      // Reset back to standard default pricing (₹2,999 / ₹1,299).
      setOriginalPrice(DEFAULT_STANDARD_MRP);
      setPrice(DEFAULT_STANDARD_SELLING_PRICE);
      setIsPriceManuallyEdited(false);
    }

    const newTypes = isNewHoodie
      ? INITIAL_HOODIE_PRODUCT_TYPES
      : (isTShirtCategory(newCat) ? INITIAL_TSHIRT_PRODUCT_TYPES : getCategoryProductTypes(newCat));
    const newColors = isNewHoodie
      ? hoodieColors
      : tshirtColors;

    let nextType = productType;
    const hasType = Boolean(productType) && newTypes.some((pt: any) => pt.name.toLowerCase() === productType.toLowerCase());
    if (!hasType) {
      nextType = '';
      setProductType('');
    }

    let nextColor = primaryColor;
    const hasColor = Boolean(primaryColor) && newColors.some((c: any) => c.name.toUpperCase() === primaryColor.toUpperCase());
    if (!hasColor) {
      nextColor = '';
      setPrimaryColor('');
    }

    if (newCat && nextType && nextColor) {
      const catCode = resolveCategoryCode(newCat?.name, newCat?.code);
      const colCode = resolveColorCode(nextColor);
      const typCode = resolveProductTypeCode(nextType);
      setSku(`${catCode}-${colCode}-${typCode}`);

      if (!isNameManuallyEdited) {
        const autoName = generateProductName(nextColor, nextType);
        setName(autoName);
        setSlug(autoName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, ''));
      }
      if (!isDescManuallyEdited) {
        setDescription(generateProductDescription({
          colorName: nextColor,
          productTypeName: nextType,
          categoryName: newCat?.name
        }));
      }
    } else {
      setSku('');
      if (!isNameManuallyEdited) {
        setName('');
        setSlug('');
      }
      if (!isDescManuallyEdited) {
        setDescription('');
      }
    }
  };

  // Product Type Change Handler (Immediate state reset and SKU recalculation)
  const handleProductTypeChange = (newType: string) => {
    setDuplicateConflict(null);
    setError('');
    setProductType(newType);

    if (categoryId && currentCategory && newType && primaryColor) {
      const catCode = resolveCategoryCode(currentCategory?.name, currentCategory?.code);
      const colCode = resolveColorCode(primaryColor);
      const typCode = resolveProductTypeCode(newType);
      setSku(`${catCode}-${colCode}-${typCode}`);

      if (!isNameManuallyEdited) {
        const autoName = generateProductName(primaryColor, newType);
        setName(autoName);
        setSlug(autoName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, ''));
      }
      if (!isDescManuallyEdited) {
        setDescription(generateProductDescription({
          colorName: primaryColor,
          productTypeName: newType,
          categoryName: currentCategory?.name
        }));
      }
    } else {
      setSku('');
      if (!isNameManuallyEdited) {
        setName('');
        setSlug('');
      }
      if (!isDescManuallyEdited) {
        setDescription('');
      }
    }
  };

  // Product Color Select Handler (Immediate state reset and SKU recalculation)
  const handleColorSelect = (newColor: string) => {
    const cleanColor = newColor.trim().toUpperCase();
    setDuplicateConflict(null);
    setError('');

    // Toggle color selection: if clicking the already selected color, deselect it back to empty
    const nextColor = primaryColor.toUpperCase() === cleanColor ? '' : cleanColor;
    setPrimaryColor(nextColor);

    if (categoryId && currentCategory && productType && nextColor) {
      const catCode = resolveCategoryCode(currentCategory?.name, currentCategory?.code);
      const colCode = resolveColorCode(nextColor);
      const typCode = resolveProductTypeCode(productType);
      setSku(`${catCode}-${colCode}-${typCode}`);

      if (!isNameManuallyEdited) {
        const autoName = generateProductName(nextColor, productType);
        setName(autoName);
        setSlug(autoName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, ''));
      }
      if (!isDescManuallyEdited) {
        setDescription(generateProductDescription({
          colorName: nextColor,
          productTypeName: productType,
          categoryName: currentCategory?.name
        }));
      }
    } else {
      setSku('');
      if (!isNameManuallyEdited) {
        setName('');
        setSlug('');
      }
      if (!isDescManuallyEdited) {
        setDescription('');
      }
    }
  };

  // Add Custom Color Handler
  const handleAddCustomColor = async () => {
    const trimmed = customColorInput.trim().toUpperCase();
    if (!trimmed) return;

    const exists = activeCategoryColors.find((c: any) => c.name.toUpperCase() === trimmed);
    if (exists) {
      handleColorSelect(exists.name.toUpperCase());
      setCustomColorInput('');
      return;
    }

    const newCol = {
      name: trimmed,
      code: resolveColorCode(trimmed),
      hex: '#64748B',
      isCustom: true
    };
    setCustomColors(prev => [...prev, newCol]);
    handleColorSelect(trimmed);
    setCustomColorInput('');

    try {
      const fd = new FormData();
      fd.append('name', trimmed);
      fd.append('code', newCol.code);
      if (newCol.hex) fd.append('hex', newCol.hex);
      fd.append('isCustom', 'true');
      await createColor(fd);
    } catch (e) {}
  };

  // Size selection toggle (Attributes/options only, no inventory tracking)
  const toggleSize = (sizeName: string) => {
    if (selectedSizes.includes(sizeName)) {
      if (selectedSizes.length > 1) {
        setSelectedSizes(prev => prev.filter(s => s !== sizeName));
      } else {
        alert('Product must have at least one size.');
      }
    } else {
      setSelectedSizes(prev => [...prev, sizeName]);
    }
  };

  // Image Upload & Management (Reorder, Set Main, Remove)
  const reindexImages = (imgs: ProductImageItem[]): ProductImageItem[] => {
    return imgs.map((img, idx) => ({
      ...img,
      sortOrder: idx,
      isPrimary: idx === 0
    }));
  };

  const processImageFiles = async (files: File[]) => {
    if (!files || files.length === 0 || isUploadingImages) return;
    setIsUploadingImages(true);

    try {
      const uploadedList: ProductImageItem[] = [];
      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        const uploadFormData = new FormData();
        uploadFormData.append('file', file);

        const res = await fetch('/api/admin/upload', {
          method: 'POST',
          body: uploadFormData
        }).catch(() => null);

        if (res && res.ok) {
          const data = await res.json().catch(() => null);
          if (data && data.url) {
            uploadedList.push({
              url: data.url,
              publicId: data.publicId,
              altText: name || file.name,
              isPrimary: false,
              sortOrder: images.length + i
            });
          }
        }
      }
      setImages(prev => reindexImages([...prev, ...uploadedList]));
    } catch {
      // fallback
    } finally {
      setIsUploadingImages(false);
    }
  };

  const removeImage = (index: number) => {
    setImages(prev => reindexImages(prev.filter((_, idx) => idx !== index)));
  };

  const moveImage = (index: number, direction: 'left' | 'right') => {
    const targetIndex = direction === 'left' ? index - 1 : index + 1;
    if (targetIndex < 0 || targetIndex >= images.length) return;

    setImages(prev => {
      const newImages = [...prev];
      const temp = newImages[index];
      newImages[index] = newImages[targetIndex];
      newImages[targetIndex] = temp;
      return reindexImages(newImages);
    });
  };

  const setAsMainImage = (index: number) => {
    if (index === 0) return;
    setImages(prev => {
      const newImages = [...prev];
      const selected = newImages.splice(index, 1)[0];
      newImages.unshift(selected);
      return reindexImages(newImages);
    });
  };

  // Open Fresh Create Form (Resets all fields cleanly to blank initial state)
  const handleOpenCreate = () => {
    setEditingId(null);
    setInitialConfig(null);
    setDuplicateConflict(null);
    setCategoryId('');
    setProductType('');
    setPrimaryColor('');
    setSelectedSizes(['S', 'M', 'L', 'XL', 'XXL']);

    setName('');
    setSlug('');
    setIsNameManuallyEdited(false);

    setSku('');
    setImages([]);
    setPrice(DEFAULT_STANDARD_SELLING_PRICE);
    setOriginalPrice(DEFAULT_STANDARD_MRP);
    setIsPriceManuallyEdited(false);
    setStatus('ACTIVE');
    setFeatured(false);
    setNewArrival(true);
    setShowSizeChart(true);
    setSizeFit('Tailored slim fit silhouette.');

    setDescription('');
    setIsDescManuallyEdited(false);

    setWashCare(DEFAULT_WASH_CARE);
    setFreeShippingText(DEFAULT_FREE_SHIPPING);
    setDeliveryHeading(DEFAULT_DELIVERY_HEADING);
    setDeliveryText(DEFAULT_DELIVERY_CONTENT);
    setReturnsHeading(DEFAULT_RETURNS_HEADING);
    setReturnPolicyText(DEFAULT_RETURNS_CONTENT);

    setError('');
    setIsEditing(true);
  };

  // Open Edit Form
  const handleOpenEdit = (product: any) => {
    setEditingId(product.id);
    const prodCatId = product.categoryId || categories[0]?.id || '';
    const prodCat = categories.find(c => c.id === prodCatId);
    const isHoodie = isHoodieCategory(prodCat);
    const prodType = product.productType || (isHoodie ? 'Unisex Hoodie' : 'Zipper Polo T-Shirt');
    const prodColor = (product.color || (isHoodie ? 'JET BLACK' : 'BABY PINK')).toUpperCase();
    const prodSku = product.sku || '';

    setInitialConfig({
      categoryId: prodCatId,
      productType: prodType,
      color: prodColor,
      sku: prodSku
    });

    setDuplicateConflict(null);
    setName(product.name || '');
    setSlug(product.slug || '');
    setIsNameManuallyEdited(false);

    setCategoryId(prodCatId);
    setProductType(prodType);
    setPrimaryColor(prodColor);
    setSku(prodSku);

    const prodPricing = getProductPricing(product);
    setPrice(prodPricing.sellingPrice ? prodPricing.sellingPrice.toString() : DEFAULT_STANDARD_SELLING_PRICE);
    setOriginalPrice(prodPricing.mrp ? prodPricing.mrp.toString() : DEFAULT_STANDARD_MRP);
    setIsPriceManuallyEdited(true);
    setStatus(product.status === 'INACTIVE' ? 'INACTIVE' : 'ACTIVE');
    setFeatured(Boolean(product.featured));
    setNewArrival(Boolean(product.newArrival));
    setShowSizeChart(product.showSizeChart !== undefined ? Boolean(product.showSizeChart) : true);
    setSizeFit(product.sizeFit || 'Tailored slim fit silhouette.');

    // Extract product sizes without inventory
    let initialSizes: string[] = ['S', 'M', 'L', 'XL', 'XXL'];
    if (Array.isArray(product.sizes) && product.sizes.length > 0) {
      initialSizes = product.sizes;
    } else if (typeof product.sizes === 'string') {
      try {
        const parsed = JSON.parse(product.sizes);
        if (Array.isArray(parsed) && parsed.length > 0) initialSizes = parsed;
      } catch (e) {}
    } else if (product.variants && Array.isArray(product.variants) && product.variants.length > 0) {
      const vSizes = Array.from(new Set(product.variants.map((v: any) => v.size).filter(Boolean))) as string[];
      if (vSizes.length > 0) initialSizes = vSizes;
    }
    setSelectedSizes(initialSizes);

    if (product.images && product.images.length > 0) {
      setImages(product.images.map((img: any, idx: number) => ({
        id: img.id,
        url: img.url,
        publicId: img.publicId,
        altText: img.altText || product.name,
        isPrimary: img.isPrimary !== undefined ? img.isPrimary : idx === 0,
        sortOrder: img.sortOrder !== undefined ? img.sortOrder : idx
      })));
    } else {
      setImages([]);
    }

    setDescription(product.description || generateProductDescription({ colorName: prodColor, productTypeName: product.productType, categoryName: product.category?.name }));
    setIsDescManuallyEdited(Boolean(product.description));

    setWashCare(product.washCare || DEFAULT_WASH_CARE);
    setFreeShippingText(product.freeShippingText || DEFAULT_FREE_SHIPPING);
    setDeliveryHeading(DEFAULT_DELIVERY_HEADING);
    setDeliveryText(product.deliveryText || DEFAULT_DELIVERY_CONTENT);
    setReturnsHeading(DEFAULT_RETURNS_HEADING);
    setReturnPolicyText(product.returnPolicyText || DEFAULT_RETURNS_CONTENT);

    setError('');
    setIsEditing(true);
  };

  // Submit Product Form & Auto-Return to List
  const handleSubmit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (loading) return;

    if (!name || !name.trim()) {
      setError('Product Name is required.');
      return;
    }
    if (!categoryId) {
      setError('Please select a Category.');
      return;
    }
    if (!productType) {
      setError('Please select a Product Type.');
      return;
    }
    if (!primaryColor) {
      setError('Please select a Product Color.');
      return;
    }
    if (selectedSizes.length === 0) {
      setError('Please select at least one available size.');
      return;
    }

    const priceCheck = validatePricing(originalPrice, price);
    if (!priceCheck.isValid) {
      setError(priceCheck.error || 'Invalid pricing configuration');
      return;
    }

    if (isCurrentDuplicate) {
      setError(duplicateConflict?.message || 'Product already exists. A product with this Category, Product Type and Color is already registered. Please edit the existing product instead.');
      return;
    }

    setLoading(true);
    setError('');

    const generatedVariants = selectedSizes.map((sz, idx) => ({
      size: sz,
      color: primaryColor,
      sku: buildVariantSku(sku, sz, idx)
    }));

    const formData = new FormData();
    if (editingId) formData.append('id', editingId);
    formData.append('name', name.trim());
    formData.append('slug', slug || name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, ''));
    formData.append('categoryId', categoryId);
    formData.append('productType', productType);
    formData.append('color', primaryColor);
    formData.append('sku', sku);

    formData.append('price', price);
    if (originalPrice) formData.append('originalPrice', originalPrice);
    formData.append('status', status);
    formData.append('featured', featured.toString());
    formData.append('newArrival', newArrival.toString());
    formData.append('showSizeChart', showSizeChart.toString());
    formData.append('sizeFit', sizeFit);

    formData.append('colors', JSON.stringify([primaryColor]));
    formData.append('sizes', JSON.stringify(selectedSizes));
    formData.append('variants', JSON.stringify(generatedVariants));
    formData.append('images', JSON.stringify(images));

    formData.append('description', description);
    formData.append('washCare', washCare);
    formData.append('freeShippingText', freeShippingText);
    formData.append('dispatchText', 'All orders are dispatched within 1–2 business days from our warehouse.');
    formData.append('deliveryText', deliveryText);
    formData.append('returnPolicyText', returnPolicyText);

    try {
      const res = await fetch('/api/admin/products', {
        method: 'POST',
        body: formData
      });
      const data = await res.json();

      if (data.success && data.product) {
        if (editingId) {
          setProducts(prev => prev.map(p => p.id === editingId ? data.product : p));
        } else {
          setProducts(prev => [data.product, ...prev]);
        }
        
        // Return to products view cleanly
        setIsEditing(false);
        setEditingId(null);
        if (typeof window !== 'undefined' && window.history) {
          window.history.replaceState(null, '', '/admin/products');
        }
        router.refresh();
        setSuccessToast(editingId ? 'Product updated successfully!' : 'Product added successfully.');
        setTimeout(() => setSuccessToast(''), 3500);
      } else {
        const rawErr = data.error || 'Failed to save product';
        const isTechnical = typeof rawErr === 'string' && (
          rawErr.includes('prisma') ||
          rawErr.includes('Prisma') ||
          rawErr.includes('TURBOPACK') ||
          rawErr.includes('invocation') ||
          rawErr.includes('Unknown field')
        );
        setError(isTechnical ? 'An unexpected error occurred while saving the product. Please try again.' : rawErr);
      }
    } catch (err: any) {
      const rawMsg = err?.message || 'Something went wrong';
      const isTechnical = typeof rawMsg === 'string' && (
        rawMsg.includes('prisma') ||
        rawMsg.includes('Prisma') ||
        rawMsg.includes('TURBOPACK') ||
        rawMsg.includes('invocation')
      );
      setError(isTechnical ? 'A network or server error occurred. Please try again.' : rawMsg);
    } finally {
      setLoading(false);
    }
  };

  // Real Database Delete Flow
  const handleConfirmDelete = async () => {
    if (!productToDelete) return;
    setIsDeleting(true);

    try {
      // Execute deletion via server action or API route
      const res = await deleteProduct(productToDelete.id);
      if (res.success) {
        setProducts(prev => prev.filter(p => p.id !== productToDelete.id));
        setSuccessToast('Product deleted successfully');
        setTimeout(() => setSuccessToast(''), 3500);
        
        // Ensure form is closed, ID is cleared, and clean URL remains /admin/products
        setIsEditing(false);
        setEditingId(null);
        if (typeof window !== 'undefined' && window.history) {
          window.history.replaceState(null, '', '/admin/products');
        }
      } else {
        setError(res.error || 'Failed to delete product');
      }
    } catch (err: any) {
      setError(err.message || 'Failed to delete product');
    } finally {
      setIsDeleting(false);
      setProductToDelete(null);
    }
  };

  const handleToggleStatus = async (product: any) => {
    const newStatus = product.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE';
    setStatusUpdatingId(product.id);
    setProducts(prev => prev.map(p => p.id === product.id ? { ...p, status: newStatus } : p));

    try {
      const formData = new FormData();
      formData.append('id', product.id);
      formData.append('status', newStatus);

      const res = await fetch('/api/admin/products', {
        method: 'POST',
        body: formData
      });
      const data = await res.json().catch(() => null);
      if (data && data.product) {
        setProducts(prev => prev.map(p => p.id === product.id ? { ...p, ...data.product, status: newStatus } : p));
      }
    } catch {
      // optimistic
    } finally {
      setStatusUpdatingId(null);
    }
  };

  // Filtered Products for List
  const filteredProducts = useMemo(() => {
    return products.filter(p => {
      if (p.status === 'DELETED') return false;
      if (searchQuery.trim() !== '') {
        const q = searchQuery.toLowerCase().trim();
        const matchesName = (p.name || '').toLowerCase().includes(q);
        const matchesSku = (p.sku || '').toLowerCase().includes(q);
        if (!matchesName && !matchesSku) return false;
      }
      if (categoryFilter !== 'ALL') {
        const matchesCat = p.categoryId === categoryFilter || p.category?.id === categoryFilter || p.category?.slug === categoryFilter;
        if (!matchesCat) return false;
      }
      if (statusFilter !== 'ALL' && p.status !== statusFilter) return false;
      return true;
    });
  }, [products, searchQuery, categoryFilter, statusFilter]);

  // Pagination for Product List
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 15;

  useEffect(() => {
    setCurrentPage(1);
  }, [searchQuery, categoryFilter, statusFilter]);

  const totalPages = Math.ceil(filteredProducts.length / itemsPerPage) || 1;
  const paginatedProducts = useMemo(() => {
    const start = (currentPage - 1) * itemsPerPage;
    return filteredProducts.slice(start, start + itemsPerPage);
  }, [filteredProducts, currentPage]);

  return (
    <div className={formStyles.pageContainer}>
      {/* Toast Notification */}
      {successToast && (
        <Portal>
          <div style={{
            position: 'fixed',
            top: '20px',
            right: '20px',
            background: '#09090b',
            color: '#FFC800',
            padding: '0.85rem 1.25rem',
            borderRadius: '8px',
            border: '1px solid #FFC800',
            boxShadow: '0 10px 25px rgba(0,0,0,0.3)',
            display: 'flex',
            alignItems: 'center',
            gap: '0.5rem',
            fontWeight: 700,
            fontSize: '0.875rem',
            zIndex: 'var(--z-toast, 2500)' as any,
          }}>
            <Check size={18} />
            <span>{successToast}</span>
          </div>
        </Portal>
      )}

      {/* Delete Confirmation Modal */}
      {productToDelete && (
        <Portal>
          <div className={formStyles.modalOverlay}>
            <div className={formStyles.modalCard}>
              <h3 className={formStyles.modalTitle}>
                <AlertTriangle size={20} color="#ef4444" />
                <span>Delete Product?</span>
              </h3>
              <div className={formStyles.modalBody}>
                Are you sure you want to delete:
                <span className={formStyles.modalProductName}>
                  {productToDelete.name}
                </span>
                This action will remove the product and its variants from the database. This action cannot be undone.
              </div>
              <div className={formStyles.modalFooter}>
                <button
                  type="button"
                  className={formStyles.secondaryBtn}
                  onClick={() => setProductToDelete(null)}
                  disabled={isDeleting}
                >
                  Cancel
                </button>
                <button
                  type="button"
                  className={formStyles.dangerRedBtn}
                  onClick={handleConfirmDelete}
                  disabled={isDeleting}
                  id="btn-confirm-delete"
                >
                  <Trash2 size={14} />
                  <span>{isDeleting ? 'Deleting...' : 'Delete Product'}</span>
                </button>
              </div>
            </div>
          </div>
        </Portal>
      )}

      {!isEditing ? (
        /* ========================================================= */
        /* ALL PRODUCTS CATALOGUE VIEW                               */
        /* ========================================================= */
        <div>
          <div className={formStyles.topBar}>
            <div className={formStyles.titleArea}>
              <h1 className={formStyles.pageTitle}>All Products</h1>
              <div className={formStyles.breadcrumbs}>
                <Link href="/admin/dashboard" className={formStyles.breadcrumbLink}>Dashboard</Link>
                <span>&gt;</span>
                <span className={formStyles.breadcrumbCurrent}>Products</span>
              </div>
            </div>
          </div>

          {/* Unified Horizontal Search, Filters & Action Toolbar */}
          <div className={formStyles.toolbarCard}>
            <div className={formStyles.toolbarLeft}>
              <div className={formStyles.toolbarSearch}>
                <Search size={16} className={formStyles.toolbarSearchIcon} />
                <input 
                  type="text" 
                  placeholder="Search products by name or SKU..." 
                  value={searchQuery}
                  onChange={e => setSearchQuery(e.target.value)}
                  className={formStyles.toolbarInput}
                />
              </div>
              <select
                value={categoryFilter}
                onChange={e => setCategoryFilter(e.target.value)}
                className={formStyles.toolbarSelect}
                aria-label="Filter by Category"
              >
                <option value="ALL">All Categories</option>
                {categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
              </select>
              <select
                value={statusFilter}
                onChange={e => setStatusFilter(e.target.value)}
                className={formStyles.toolbarSelect}
                aria-label="Filter by Status"
              >
                <option value="ALL">All Status</option>
                <option value="ACTIVE">Active</option>
                <option value="INACTIVE">Inactive</option>
              </select>
            </div>

            <div className={formStyles.toolbarRight}>
              <button 
                type="button" 
                className={formStyles.addProductBtn}
                onClick={handleOpenCreate}
                id="btn-add-product"
              >
                <Plus size={16} />
                <span>Add Product</span>
              </button>
            </div>
          </div>

          {/* Products Table Card */}
          <div className={formStyles.tableCard}>
            <table className={formStyles.catalogTable}>
              <thead>
                <tr>
                  <th className={formStyles.colProduct}>Product</th>
                  <th className={formStyles.colCategory}>Category</th>
                  <th className={formStyles.colType}>Product Type</th>
                  <th className={formStyles.colColor}>Color</th>
                  <th className={formStyles.colSku}>SKU</th>
                  <th className={formStyles.colSizes}>Available Sizes</th>
                  <th className={formStyles.colVisibility}>Visibility</th>
                  <th className={formStyles.colActions}>Actions</th>
                </tr>
              </thead>
              <tbody>
                {filteredProducts.length === 0 ? (
                  <tr>
                    <td colSpan={8} style={{ textAlign: 'center', padding: '3.5rem 1rem', color: '#71717a' }}>
                      <Package size={32} style={{ margin: '0 auto 0.75rem', opacity: 0.4 }} />
                      <div style={{ fontWeight: 600, color: '#3f3f46', marginBottom: '0.25rem' }}>No products found</div>
                      <div style={{ fontSize: '0.8rem' }}>Try adjusting your search query or filters.</div>
                    </td>
                  </tr>
                ) : (
                  paginatedProducts.map(p => {
                    const primaryImg = p.images?.find((img: any) => img.isPrimary)?.url || p.images?.[0]?.url;
                    const pricing = getProductPricing(p);
                    let pSizes: string[] = [];
                    if (Array.isArray(p.sizes) && p.sizes.length > 0) pSizes = p.sizes;
                    else if (typeof p.sizes === 'string') {
                      try { const parsed = JSON.parse(p.sizes); if (Array.isArray(parsed)) pSizes = parsed; } catch (e) {}
                    } else if (p.variants && Array.isArray(p.variants)) {
                      pSizes = Array.from(new Set(p.variants.map((v: any) => v.size).filter(Boolean))) as string[];
                    }
                    if (pSizes.length === 0) pSizes = ['Free Size'];

                    return (
                      <tr key={p.id}>
                        <td className={formStyles.colProduct}>
                          <div className={formStyles.productCell}>
                            <div className={formStyles.productThumb}>
                              {primaryImg ? (
                                <img src={primaryImg} alt={p.name} />
                              ) : (
                                <Package size={18} color="#a1a1aa" />
                              )}
                            </div>
                            <div className={formStyles.productInfo}>
                              <span className={formStyles.productNameText} title={p.name}>{p.name}</span>
                              <span className={formStyles.productPriceText}>₹{pricing.sellingPrice.toLocaleString('en-IN')}</span>
                            </div>
                          </div>
                        </td>
                        <td className={formStyles.colCategory}>
                          <span style={{ fontWeight: 500, color: '#334155' }}>
                            {p.category?.name || 'Uncategorized'}
                          </span>
                        </td>
                        <td className={formStyles.colType}>
                          <span style={{ fontWeight: 500, color: '#334155' }}>
                            {p.productType || 'Standard'}
                          </span>
                        </td>
                        <td className={formStyles.colColor}>
                          <div className={formStyles.colorCell}>
                            <span 
                              className={formStyles.colorDot} 
                              style={{ backgroundColor: INITIAL_PREDEFINED_COLORS.find(c => c.name === p.color?.toUpperCase())?.hex || '#a1a1aa' }} 
                            />
                            <span>{formatColorTitleCase(p.color) || 'Standard'}</span>
                          </div>
                        </td>
                        <td className={formStyles.colSku}>
                          <span className={formStyles.skuBadge}>
                            {p.sku || 'N/A'}
                          </span>
                        </td>
                        <td className={formStyles.colSizes}>
                          <div style={{ display: 'flex', gap: '4px', flexWrap: 'wrap', maxWidth: '160px' }}>
                            {pSizes.slice(0, 6).map((sz: string) => (
                              <span key={sz} style={{ fontSize: '10px', fontWeight: 700, padding: '2px 6px', background: '#f4f4f5', borderRadius: '4px', color: '#52525b', border: '1px solid #e4e4e7' }}>
                                {sz}
                              </span>
                            ))}
                          </div>
                        </td>
                        <td className={formStyles.colVisibility}>
                          <button
                            type="button"
                            onClick={() => handleToggleStatus(p)}
                            disabled={statusUpdatingId === p.id}
                            className={p.status === 'ACTIVE' ? formStyles.activeBtn : formStyles.inactiveBtn}
                            title="Toggle Active/Inactive Visibility"
                          >
                            <span>{p.status === 'ACTIVE' ? '● Active' : '○ Inactive'}</span>
                          </button>
                        </td>
                        <td className={formStyles.colActions}>
                          <div className={formStyles.actionsGroup}>
                            <button 
                              type="button"
                              onClick={() => handleOpenEdit(p)}
                              className={formStyles.actionBtn}
                              title="Edit Product"
                            >
                              <Edit size={14} />
                            </button>
                            <button 
                              type="button"
                              onClick={() => setProductToDelete(p)}
                              className={formStyles.deleteActionBtn}
                              title="Delete Product"
                              id={`btn-delete-${p.id}`}
                            >
                              <Trash2 size={14} />
                            </button>
                          </div>
                        </td>
                      </tr>
                    );
                  })
                )}
              </tbody>
            </table>

            {/* Table Pagination Footer */}
            <div className={formStyles.tableFooter}>
              <div className={formStyles.paginationInfo}>
                Showing {filteredProducts.length === 0 ? 0 : (currentPage - 1) * itemsPerPage + 1} to {Math.min(currentPage * itemsPerPage, filteredProducts.length)} of {filteredProducts.length} {filteredProducts.length === 1 ? 'product' : 'products'}
              </div>
              {totalPages > 1 && (
                <div className={formStyles.paginationControls}>
                  <button
                    type="button"
                    className={formStyles.pageNavBtn}
                    onClick={() => setCurrentPage(p => Math.max(p - 1, 1))}
                    disabled={currentPage === 1}
                  >
                    <ChevronLeft size={14} />
                    <span>Prev</span>
                  </button>
                  <span className={formStyles.pageIndicator}>
                    Page {currentPage} of {totalPages}
                  </span>
                  <button
                    type="button"
                    className={formStyles.pageNavBtn}
                    onClick={() => setCurrentPage(p => Math.min(p + 1, totalPages))}
                    disabled={currentPage === totalPages}
                  >
                    <span>Next</span>
                    <ChevronRight size={14} />
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
      ) : (
        /* ========================================================= */
        /* ADD / EDIT PRODUCT FORM                                   */
        /* ========================================================= */
        <div>
          {/* Top Bar */}
          <div className={formStyles.topBar}>
            <div className={formStyles.titleArea}>
              <h1 className={formStyles.pageTitle}>
                {editingId ? 'Edit Product' : 'Add New Product'}
              </h1>
              <div className={formStyles.breadcrumbs}>
                <Link href="/admin/dashboard" className={formStyles.breadcrumbLink}>Dashboard</Link>
                <span>&gt;</span>
                <Link href="/admin/products" onClick={() => setIsEditing(false)} className={formStyles.breadcrumbLink}>Products</Link>
                <span>&gt;</span>
                <span className={formStyles.breadcrumbCurrent}>Add New Product</span>
              </div>
            </div>

            <div className={formStyles.topActions}>
              <button 
                type="button" 
                className={formStyles.secondaryBtn}
                onClick={() => { setIsEditing(false); setEditingId(null); }}
              >
                <ArrowLeft size={15} />
                <span>Back to Products</span>
              </button>
              {editingId && (
                <button
                  type="button"
                  className={formStyles.dangerRedBtn}
                  onClick={() => setProductToDelete({ id: editingId, name })}
                >
                  <Trash2 size={14} />
                  <span>Delete</span>
                </button>
              )}
              <button 
                type="button" 
                className={formStyles.primaryYellowBtn}
                onClick={() => handleSubmit()}
                disabled={loading || isUploadingImages || Boolean(isCurrentDuplicate)}
                title={isCurrentDuplicate ? 'Cannot save duplicate product configuration' : undefined}
                id="btn-save-product-top"
              >
                <Save size={16} />
                <span>{loading ? 'Saving...' : editingId ? 'Save Changes' : 'Create Product'}</span>
                <ChevronDown size={14} />
              </button>
            </div>
          </div>

          {/* Stepper (9 Steps) */}
          <div className={formStyles.stepperContainer}>
            <div className={formStyles.stepperTrack}>
              {steps.map((st, idx) => (
                <div key={st.id} style={{ display: 'flex', alignItems: 'center', gap: '0.65rem', flex: idx < steps.length - 1 ? 1 : 'none' }}>
                  <button
                    type="button"
                    className={formStyles.stepItem}
                    onClick={() => scrollToStep(st.id)}
                  >
                    <div className={`${formStyles.stepBadge} ${st.isDone ? formStyles.stepBadgeActive : formStyles.stepBadgePending}`}>
                      {st.num}
                    </div>
                    <div className={formStyles.stepTextGroup}>
                      <span className={formStyles.stepTitle}>{st.title}</span>
                      <span className={formStyles.stepSubtitle}>{st.subtitle}</span>
                    </div>
                  </button>
                  {idx < steps.length - 1 && (
                    <div className={`${formStyles.stepConnector} ${st.isDone ? formStyles.stepConnectorActive : ''}`} />
                  )}
                </div>
              ))}
            </div>
          </div>

          {error && (
            <div style={{ padding: '0.75rem 1rem', background: '#fef2f2', border: '1px solid #fecaca', color: '#991b1b', borderRadius: '6px', marginBottom: '1rem', fontWeight: 600, fontSize: '0.875rem' }}>
              <AlertTriangle size={16} style={{ display: 'inline', marginRight: '0.4rem', verticalAlign: 'middle' }} />
              <span>{error}</span>
            </div>
          )}

          {isCurrentDuplicate && (
            <div 
              id="duplicate-product-alert"
              style={{
                padding: '1.25rem',
                background: '#fff1f2',
                border: '1.5px solid #f43f5e',
                borderRadius: '10px',
                marginBottom: '1.25rem',
                boxShadow: '0 4px 12px rgba(244, 63, 94, 0.08)'
              }}
            >
              <div style={{ display: 'flex', alignItems: 'flex-start', gap: '0.85rem' }}>
                <div style={{ background: '#f43f5e', color: '#fff', borderRadius: '50%', padding: '0.35rem', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <AlertTriangle size={20} />
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: '1rem', fontWeight: 800, color: '#9f1239', letterSpacing: '-0.01em' }}>
                    Product already exists
                  </div>
                  <div style={{ fontSize: '0.85rem', color: '#be123c', marginTop: '0.15rem', fontWeight: 500 }}>
                    This product configuration is already registered.
                  </div>

                  <div style={{ 
                    marginTop: '0.75rem', 
                    padding: '0.75rem 1rem', 
                    background: '#ffffff', 
                    borderRadius: '8px', 
                    border: '1px solid #fecdd3',
                    fontSize: '0.825rem',
                    color: '#374151',
                    display: 'grid',
                    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
                    gap: '0.5rem'
                  }}>
                    <div>
                      <span style={{ fontWeight: 700, color: '#6b7280' }}>Category: </span>
                      <span style={{ fontWeight: 800, color: '#111827' }}>{duplicateConflict?.existingProduct?.categoryName || duplicateConflict?.existingProduct?.category || currentCategory?.name || 'N/A'}</span>
                    </div>
                    <div>
                      <span style={{ fontWeight: 700, color: '#6b7280' }}>Product Type: </span>
                      <span style={{ fontWeight: 800, color: '#111827' }}>{duplicateConflict?.existingProduct?.productType || productType}</span>
                    </div>
                    <div>
                      <span style={{ fontWeight: 700, color: '#6b7280' }}>Color: </span>
                      <span style={{ fontWeight: 800, color: '#111827' }}>{duplicateConflict?.existingProduct?.color || primaryColor}</span>
                    </div>
                    <div>
                      <span style={{ fontWeight: 700, color: '#6b7280' }}>Existing SKU: </span>
                      <span style={{ fontFamily: 'monospace', fontWeight: 800, color: '#e11d48', background: '#ffe4e6', padding: '0.1rem 0.35rem', borderRadius: '4px' }}>
                        {duplicateConflict?.existingProduct?.sku || 'N/A'}
                      </span>
                    </div>
                  </div>

                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: '0.75rem', flexWrap: 'wrap', gap: '0.5rem' }}>
                    <div style={{ fontSize: '0.825rem', color: '#881337', fontWeight: 600 }}>
                      Please edit the existing product instead of creating a duplicate.
                    </div>
                    {duplicateConflict?.existingProduct?.id && (
                      <button
                        type="button"
                        onClick={() => {
                          const existingProd = products.find(p => p.id === duplicateConflict?.existingProduct?.id);
                          if (existingProd) {
                            handleOpenEdit(existingProd);
                          } else {
                            fetch(`/api/admin/products?id=${duplicateConflict?.existingProduct?.id}`)
                              .then(r => r.json())
                              .then(d => { if (d.product) handleOpenEdit(d.product); })
                              .catch(console.error);
                          }
                        }}
                        style={{
                          padding: '0.4rem 0.85rem',
                          background: '#be123c',
                          color: '#ffffff',
                          border: 'none',
                          borderRadius: '6px',
                          fontSize: '0.775rem',
                          fontWeight: 700,
                          cursor: 'pointer',
                          display: 'inline-flex',
                          alignItems: 'center',
                          gap: '0.35rem'
                        }}
                      >
                        <Edit size={13} />
                        <span>Edit Existing Product</span>
                      </button>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}

          <form onSubmit={handleSubmit}>
            {/* ======================================================= */}
            {/* ROW 1: CATEGORY | PRODUCT TYPE / STYLE                  */}
            {/* ======================================================= */}
            <div className={formStyles.twoColGrid} id="step-1">
              {/* Category */}
              <div className={formStyles.formCard}>
                <label className={formStyles.cardLabel}>
                  <span>Category</span>
                  <span className={formStyles.requiredStar}>*</span>
                </label>
                <select
                  className={formStyles.formSelect}
                  value={categoryId}
                  onChange={e => handleCategoryChange(e.target.value)}
                  id="field-category"
                >
                  <option value="">-- Select Category --</option>
                  {categories.map(c => (
                    <option key={c.id} value={c.id}>{c.name}</option>
                  ))}
                </select>
              </div>

              {/* Product Type / Style */}
              <div className={formStyles.formCard} id="step-2">
                <label className={formStyles.cardLabel}>
                  <span>Product Type / Style</span>
                  <span className={formStyles.requiredStar}>*</span>
                </label>
                <select
                  className={formStyles.formSelect}
                  value={productType}
                  onChange={e => handleProductTypeChange(e.target.value)}
                  id="field-product-type"
                  disabled={!categoryId}
                >
                  <option value="">{categoryId ? '-- Select Product Type / Style --' : '-- Select Category First --'}</option>
                  {availableProductTypes.map((pt: any) => (
                    <option key={pt.name} value={pt.name}>{pt.name}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* ======================================================= */}
            {/* ROW 2: PRODUCT COLOR (VISIBLE GRID) | NAME & SKU        */}
            {/* ======================================================= */}
            <div className={formStyles.twoColGrid} id="step-3">
              {/* LEFT: Full Visible Color Grid with + Add Custom Color */}
              <div className={formStyles.formCard}>
                <label className={formStyles.cardLabel}>
                  <span>Product Color</span>
                  <span className={formStyles.requiredStar}>*</span>
                </label>

                {/* Visible Grid of all category colors */}
                <div className={formStyles.colorSelectionGrid}>
                  {activeCategoryColors.length === 0 ? (
                    <div style={{ color: '#64748b', fontSize: '0.85rem', padding: '0.5rem 0', gridColumn: '1 / -1' }}>
                      {categoryId ? 'No colors configured for this category.' : 'Please select a Category above to view available colors.'}
                    </div>
                  ) : (
                    activeCategoryColors.map((c: any) => {
                      const isSelected = Boolean(primaryColor && primaryColor.toUpperCase() === c.name.toUpperCase());
                      return (
                        <button
                          key={c.name}
                          type="button"
                          className={`${formStyles.colorPillItem} ${isSelected ? formStyles.colorPillItemActive : ''}`}
                          onClick={() => handleColorSelect(c.name.toUpperCase())}
                        >
                          <span 
                            className={formStyles.colorDot}
                            style={{ backgroundColor: c.hex || '#64748B' }}
                          />
                          <span className={formStyles.colorPillText}>
                            {c.numberLabel ? `${c.numberLabel} — ${c.name.toUpperCase()}` : c.name.toUpperCase()}
                          </span>
                          {isSelected && <Check size={11} strokeWidth={3} style={{ marginLeft: 'auto', color: '#000000' }} />}
                        </button>
                      );
                    })
                  )}
                </div>

                {/* + Add Custom Color Input Row */}
                <div className={formStyles.customColorRow}>
                  <input
                    type="text"
                    placeholder="+ ADD CUSTOM COLOR (e.g. SAGE GREEN)"
                    className={formStyles.customColorInput}
                    value={customColorInput}
                    onChange={e => setCustomColorInput(e.target.value)}
                    id="input-custom-color"
                  />
                  <button
                    type="button"
                    className={formStyles.customColorAddBtn}
                    onClick={handleAddCustomColor}
                    id="btn-add-custom-color"
                  >
                    Add Color
                  </button>
                </div>
              </div>

              {/* RIGHT: Product Name & Product SKU */}
              <div className={formStyles.formCard} id="step-4">
                <label className={formStyles.cardLabel}>
                  <span>Product Name</span>
                  <span className={formStyles.requiredStar}>*</span>
                </label>
                <div className={formStyles.inputWithButton}>
                  <input
                    type="text"
                    className={formStyles.formInput}
                    value={name}
                    onChange={e => handleNameChange(e.target.value)}
                    placeholder="e.g. Baby Pink Zipper Polo T-Shirt"
                    required
                    id="field-product-name"
                  />
                  <button
                    type="button"
                    className={formStyles.inputActionBtn}
                    onClick={handleRegenerateName}
                    title="Regenerate Name"
                  >
                    <RefreshCw size={12} />
                    <span>Regenerate</span>
                  </button>
                </div>
                <span className={formStyles.helperText}>
                  Automatically generated from Category, Product Type &amp; Color
                </span>

                <div style={{ marginTop: '0.85rem' }}>
                  <label className={formStyles.cardLabel}>
                    <span>Product SKU</span>
                    <span className={formStyles.requiredStar}>*</span>
                  </label>
                  <div className={formStyles.inputWithButton}>
                    <input
                      type="text"
                      className={formStyles.formInput}
                      value={sku}
                      readOnly
                      id="field-sku"
                      style={isCurrentDuplicate ? { borderColor: '#f43f5e', background: '#fff1f2', color: '#9f1239', fontWeight: 700 } : {}}
                    />
                    <button
                      type="button"
                      className={formStyles.inputActionBtn}
                      onClick={() => handleCopySku(sku)}
                      id="btn-copy-sku"
                    >
                      {copiedSku === sku ? <Check size={12} color="#16a34a" /> : <Copy size={12} />}
                      <span>{copiedSku === sku ? 'Copied' : 'Copy'}</span>
                    </button>
                  </div>
                  {isCurrentDuplicate ? (
                    <span style={{ color: '#e11d48', fontSize: '0.75rem', fontWeight: 700, display: 'block', marginTop: '0.35rem' }}>
                      ⚠ Product already exists. Existing SKU: {duplicateConflict?.existingProduct?.sku}
                    </span>
                  ) : (
                    <span className={formStyles.helperText}>
                      Automatically generated from Category, Product Type &amp; Color • Unique SKU
                    </span>
                  )}
                </div>
              </div>
            </div>

            {/* ======================================================= */}
            {/* ROW 3: PRICING & DISCOUNT | AVAILABLE SIZES             */}
            {/* ======================================================= */}
            <div className={formStyles.twoColGrid} id="step-5">
              {/* LEFT: Pricing & Discount */}
              <div className={formStyles.formCard}>
                <div style={{ fontWeight: 800, fontSize: '0.9rem', marginBottom: '0.85rem' }}>
                  Pricing &amp; Discount
                </div>

                <div className={formStyles.pricingInputsGrid}>
                  <div>
                    <label className={formStyles.cardLabel}>
                      <span>Original Price (MRP ₹)</span>
                      <span className={formStyles.requiredStar}>*</span>
                    </label>
                    <input
                      type="number"
                      min="0"
                      step="0.01"
                      className={formStyles.formInput}
                      value={originalPrice}
                      onChange={e => {
                        setOriginalPrice(e.target.value);
                        setIsPriceManuallyEdited(true);
                      }}
                      placeholder={isHoodieCategory(currentCategory) ? "3999.00" : "2999.00"}
                      id="field-mrp"
                    />
                  </div>

                  <div>
                    <label className={formStyles.cardLabel}>
                      <span>Selling Price (₹)</span>
                      <span className={formStyles.requiredStar}>*</span>
                    </label>
                    <input
                      type="number"
                      min="0"
                      step="0.01"
                      className={formStyles.formInput}
                      value={price}
                      onChange={e => {
                        setPrice(e.target.value);
                        setIsPriceManuallyEdited(true);
                      }}
                      placeholder={isHoodieCategory(currentCategory) ? "1999.00" : "1299.00"}
                      required
                      id="field-price"
                    />
                  </div>
                </div>

                {pricingValidationError && (
                  <div style={{
                    marginBottom: '0.65rem',
                    padding: '0.45rem 0.65rem',
                    background: '#fef2f2',
                    border: '1px solid #fecaca',
                    borderRadius: '6px',
                    color: '#991b1b',
                    fontSize: '0.75rem',
                    fontWeight: 600,
                    display: 'flex',
                    alignItems: 'center',
                    gap: '0.35rem'
                  }}>
                    <AlertTriangle size={14} />
                    <span>{pricingValidationError}</span>
                  </div>
                )}

                <div>
                  <div style={{ fontSize: '0.75rem', fontWeight: 700, color: '#71717a', marginBottom: '0.2rem' }}>Discount</div>
                  <div className={formStyles.discountRedTag}>{calculatedDiscount}% OFF</div>
                  {calculatedSavings > 0 && (
                    <div className={formStyles.savingsText} style={{ fontWeight: 700, color: '#09090b', marginTop: '0.25rem' }}>
                      You Save ₹{calculatedSavings.toLocaleString('en-IN')}
                    </div>
                  )}
                  <span className={formStyles.helperText}>
                    Automatically calculated from MRP and Selling Price
                  </span>
                </div>
              </div>

              {/* RIGHT: Available Sizes */}
              <div className={formStyles.formCard} id="step-6">
                <label className={formStyles.cardLabel}>
                  <span>Available Sizes</span>
                  <span className={formStyles.requiredStar}>*</span>
                </label>
                <div className={formStyles.sizesRow}>
                  {ALL_SIZES.map(sz => {
                    const isSelected = selectedSizes.includes(sz);
                    return (
                      <button
                        key={sz}
                        type="button"
                        className={`${formStyles.sizeCheckboxPill} ${isSelected ? formStyles.sizeCheckboxPillActive : ''}`}
                        onClick={() => toggleSize(sz)}
                      >
                        <span className={`${formStyles.sizeCheckboxBox} ${isSelected ? formStyles.sizeCheckboxBoxActive : ''}`}>
                          {isSelected && <Check size={10} strokeWidth={3} />}
                        </span>
                        <span>{sz}</span>
                      </button>
                    );
                  })}
                </div>
              </div>
            </div>

            {/* ======================================================= */}
            {/* ROW 4: PRODUCT IMAGES (LIGHT YELLOW BG + HORIZONTAL)    */}
            {/* ======================================================= */}
            <div className={formStyles.imagesSectionCard} id="step-7">
              <label className={formStyles.cardLabel}>
                <span>Product Images</span>
                <span className={formStyles.requiredStar}>*</span>
              </label>

              <div className={formStyles.imagesFlexRow}>
                {/* Upload Drop Box */}
                <div 
                  className={formStyles.uploadDropBox}
                  onClick={() => fileInputRef.current?.click()}
                >
                  <UploadCloud size={28} className={formStyles.uploadIcon} />
                  <div className={formStyles.uploadTitle}>
                    {isUploadingImages ? 'Uploading...' : 'Upload Product Images'}
                  </div>
                  <div className={formStyles.uploadSubtitle}>
                    Upload multiple product images at once
                  </div>
                  <div className={formStyles.uploadDesc}>
                    PNG, JPG, WEBP • Max 5MB each
                  </div>
                  <input
                    ref={fileInputRef}
                    type="file"
                    multiple
                    accept="image/*"
                    style={{ display: 'none' }}
                    onChange={e => {
                      if (e.target.files && e.target.files.length > 0) {
                        processImageFiles(Array.from(e.target.files));
                      }
                    }}
                  />
                </div>

                {/* Uploaded Images Preview Strip (Horizontal 1, 2, 3, 4...) */}
                {images.map((img, idx) => (
                  <div key={img.url + idx} className={formStyles.imagePreviewCard}>
                    <img src={img.url} alt={`Product image ${idx + 1}`} className={formStyles.imagePreviewImg} />
                    
                    {/* Order / Main Badge */}
                    <div className={`${formStyles.imageOrderBadge} ${idx === 0 ? formStyles.mainBadge : ''}`}>
                      {idx === 0 ? '1 — MAIN' : `${idx + 1}`}
                    </div>

                    {/* Delete Action */}
                    <button
                      type="button"
                      className={formStyles.imageDeleteBtn}
                      onClick={() => removeImage(idx)}
                      title="Remove image"
                    >
                      ✕
                    </button>

                    {/* Controls Overlay (Reorder / Set Main) */}
                    <div className={formStyles.imageControlsOverlay}>
                      <button
                        type="button"
                        className={formStyles.imageMoveBtn}
                        onClick={() => moveImage(idx, 'left')}
                        disabled={idx === 0}
                        title="Move left"
                      >
                        <ChevronLeft size={13} />
                      </button>
                      
                      {idx !== 0 && (
                        <button
                          type="button"
                          className={formStyles.imageMoveBtn}
                          onClick={() => setAsMainImage(idx)}
                          title="Set as Main Image"
                          style={{ width: 'auto', padding: '0 4px', fontSize: '9px', fontWeight: 800 }}
                        >
                          ★ Main
                        </button>
                      )}

                      <button
                        type="button"
                        className={formStyles.imageMoveBtn}
                        onClick={() => moveImage(idx, 'right')}
                        disabled={idx === images.length - 1}
                        title="Move right"
                      >
                        <ChevronRight size={13} />
                      </button>
                    </div>
                  </div>
                ))}

                {/* Add More Images Button */}
                <button
                  type="button"
                  className={formStyles.addMoreBtn}
                  onClick={() => fileInputRef.current?.click()}
                >
                  <Plus size={20} color="#FFC800" />
                  <span>+ Add More</span>
                  <span style={{ fontSize: '0.675rem', color: '#71717a' }}>Click to upload</span>
                </button>
              </div>
            </div>

            {/* ======================================================= */}
            {/* 1. PRODUCT DESCRIPTION (FULL-WIDTH SINGLE CARD)         */}
            {/* ======================================================= */}
            <div className={formStyles.fullWidthCard} id="step-8">
              <div className={formStyles.sectionHeaderRow}>
                <div className={formStyles.sectionHeaderLeft}>
                  <span className={formStyles.yellowCircleIcon}><FileText size={12} /></span>
                  <span>Product Description</span>
                  <span className={formStyles.aiBadge}>AI</span>
                  <span className={formStyles.sectionSubtitle}>Auto-generated based on selected details</span>
                </div>
                <button
                  type="button"
                  className={formStyles.sectionActionBtn}
                  onClick={handleRegenerateDescription}
                  title="Regenerate Description"
                >
                  <RefreshCw size={11} />
                  <span>Regenerate</span>
                </button>
              </div>
              <textarea
                rows={3}
                className={formStyles.sectionTextarea}
                value={description}
                onChange={e => { setDescription(e.target.value); setIsDescManuallyEdited(true); }}
                placeholder="Product description..."
              />
              <span className={formStyles.helperText}>
                Automatically generated from selected product details
              </span>
            </div>

            {/* ======================================================= */}
            {/* 2. WASH CARE (FULL-WIDTH CARD)                          */}
            {/* ======================================================= */}
            <div className={formStyles.fullWidthCard}>
              <div className={formStyles.sectionHeaderRow}>
                <div className={formStyles.sectionHeaderLeft}>
                  <span className={formStyles.yellowCircleIcon}><RotateCcw size={12} /></span>
                  <span>Wash Care</span>
                  <span className={formStyles.sectionSubtitle}>Fabric care and washing instructions</span>
                </div>
                <button
                  type="button"
                  className={formStyles.sectionActionBtn}
                  onClick={() => setWashCare(DEFAULT_WASH_CARE)}
                >
                  Reset to Default
                </button>
              </div>
              <textarea
                rows={2}
                className={formStyles.sectionTextarea}
                value={washCare}
                onChange={e => setWashCare(e.target.value)}
              />
            </div>

            {/* ======================================================= */}
            {/* 3. FREE SHIPPING (FULL-WIDTH CARD)                      */}
            {/* ======================================================= */}
            <div className={formStyles.fullWidthCard}>
              <div className={formStyles.sectionHeaderRow}>
                <div className={formStyles.sectionHeaderLeft}>
                  <span className={formStyles.yellowCircleIcon}><Truck size={12} /></span>
                  <span>Free Shipping</span>
                  <span className={formStyles.sectionSubtitle}>Shipping policy statement</span>
                </div>
                <button
                  type="button"
                  className={formStyles.sectionActionBtn}
                  onClick={() => setFreeShippingText(DEFAULT_FREE_SHIPPING)}
                >
                  Reset to Default
                </button>
              </div>
              <input
                type="text"
                className={formStyles.formInput}
                value={freeShippingText}
                onChange={e => setFreeShippingText(e.target.value)}
              />
            </div>

            {/* ======================================================= */}
            {/* 4. 2–5 DAYS DELIVERY (FULL-WIDTH CARD)                  */}
            {/* ======================================================= */}
            <div className={formStyles.fullWidthCard}>
              <div className={formStyles.sectionHeaderRow}>
                <div className={formStyles.sectionHeaderLeft}>
                  <span className={formStyles.yellowCircleIcon}><Truck size={12} /></span>
                  <span>{deliveryHeading}</span>
                  <span className={formStyles.sectionSubtitle}>Dispatch and delivery timeline</span>
                </div>
                <button
                  type="button"
                  className={formStyles.sectionActionBtn}
                  onClick={() => {
                    setDeliveryHeading(DEFAULT_DELIVERY_HEADING);
                    setDeliveryText(DEFAULT_DELIVERY_CONTENT);
                  }}
                >
                  Reset to Default
                </button>
              </div>
              <div style={{ marginBottom: '0.65rem' }}>
                <label style={{ display: 'block', fontSize: '0.75rem', fontWeight: 700, color: '#71717a', marginBottom: '0.25rem' }}>Section Heading</label>
                <input
                  type="text"
                  className={formStyles.formInput}
                  value={deliveryHeading}
                  onChange={e => setDeliveryHeading(e.target.value)}
                />
              </div>
              <div>
                <label style={{ display: 'block', fontSize: '0.75rem', fontWeight: 700, color: '#71717a', marginBottom: '0.25rem' }}>Delivery Policy Content</label>
                <textarea
                  rows={2}
                  className={formStyles.sectionTextarea}
                  value={deliveryText}
                  onChange={e => setDeliveryText(e.target.value)}
                />
              </div>
            </div>

            {/* ======================================================= */}
            {/* 5. 7 DAYS RETURNS & EXCHANGE (FULL-WIDTH CARD)          */}
            {/* ======================================================= */}
            <div className={formStyles.fullWidthCard}>
              <div className={formStyles.sectionHeaderRow}>
                <div className={formStyles.sectionHeaderLeft}>
                  <span className={formStyles.yellowCircleIcon}><RotateCcw size={12} /></span>
                  <span>{returnsHeading}</span>
                  <span className={formStyles.sectionSubtitle}>Customer return and exchange timeline</span>
                </div>
                <button
                  type="button"
                  className={formStyles.sectionActionBtn}
                  onClick={() => {
                    setReturnsHeading(DEFAULT_RETURNS_HEADING);
                    setReturnPolicyText(DEFAULT_RETURNS_CONTENT);
                  }}
                >
                  Reset to Default
                </button>
              </div>
              <div style={{ marginBottom: '0.65rem' }}>
                <label style={{ display: 'block', fontSize: '0.75rem', fontWeight: 700, color: '#71717a', marginBottom: '0.25rem' }}>Section Heading</label>
                <input
                  type="text"
                  className={formStyles.formInput}
                  value={returnsHeading}
                  onChange={e => setReturnsHeading(e.target.value)}
                />
              </div>
              <div>
                <label style={{ display: 'block', fontSize: '0.75rem', fontWeight: 700, color: '#71717a', marginBottom: '0.25rem' }}>Returns Policy Content</label>
                <textarea
                  rows={2}
                  className={formStyles.sectionTextarea}
                  value={returnPolicyText}
                  onChange={e => setReturnPolicyText(e.target.value)}
                />
              </div>
            </div>

            {/* ======================================================= */}
            {/* 6. PRODUCT STATUS & BADGES (FULL-WIDTH CARD)            */}
            {/* ======================================================= */}
            <div className={formStyles.fullWidthCard} id="step-9">
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '1rem', borderBottom: '1px solid #f4f4f5', paddingBottom: '1rem', marginBottom: '1rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                  {status === 'ACTIVE' ? <Eye size={22} color="#FFC800" /> : <EyeOff size={22} color="#71717a" />}
                  <div>
                    <div style={{ fontSize: '0.9rem', fontWeight: 800, color: status === 'ACTIVE' ? '#000000' : '#71717a' }}>
                      {status === 'ACTIVE' ? 'Active' : 'Inactive'}
                    </div>
                    <div style={{ fontSize: '0.75rem', color: '#71717a', marginTop: '2px' }}>
                      {status === 'ACTIVE' ? 'Product is visible on the website.' : 'Product is hidden from the website.'}
                    </div>
                  </div>
                </div>

                <div>
                  <label className={formStyles.switchToggle}>
                    <input
                      type="checkbox"
                      checked={status === 'ACTIVE'}
                      onChange={e => setStatus(e.target.checked ? 'ACTIVE' : 'INACTIVE')}
                      id="field-status-toggle"
                    />
                    <span className={formStyles.switchSlider} />
                  </label>
                </div>
              </div>

              {/* Product Flags: Featured, New Arrival, Size Chart */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '1rem', marginBottom: '1rem' }}>
                <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', padding: '0.65rem 0.85rem', background: '#fafafa', borderRadius: '8px', border: '1px solid #e4e4e7' }}>
                  <input
                    type="checkbox"
                    checked={featured}
                    onChange={e => setFeatured(e.target.checked)}
                    id="field-featured-toggle"
                  />
                  <div>
                    <div style={{ fontSize: '0.8rem', fontWeight: 700 }}>Featured Product</div>
                    <div style={{ fontSize: '0.7rem', color: '#71717a' }}>Showcase in featured highlights</div>
                  </div>
                </label>

                <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', padding: '0.65rem 0.85rem', background: '#fafafa', borderRadius: '8px', border: '1px solid #e4e4e7' }}>
                  <input
                    type="checkbox"
                    checked={newArrival}
                    onChange={e => setNewArrival(e.target.checked)}
                    id="field-newarrival-toggle"
                  />
                  <div>
                    <div style={{ fontSize: '0.8rem', fontWeight: 700 }}>New Arrival</div>
                    <div style={{ fontSize: '0.7rem', color: '#71717a' }}>Mark with New Arrival tag</div>
                  </div>
                </label>

                <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer', padding: '0.65rem 0.85rem', background: '#fafafa', borderRadius: '8px', border: '1px solid #e4e4e7' }}>
                  <input
                    type="checkbox"
                    checked={showSizeChart}
                    onChange={e => setShowSizeChart(e.target.checked)}
                    id="field-sizechart-toggle"
                  />
                  <div>
                    <div style={{ fontSize: '0.8rem', fontWeight: 700 }}>Size Chart</div>
                    <div style={{ fontSize: '0.7rem', color: '#71717a' }}>Display size chart guide</div>
                  </div>
                </label>
              </div>

              <div>
                <label style={{ display: 'block', fontSize: '0.75rem', fontWeight: 700, color: '#71717a', marginBottom: '0.25rem' }}>Size & Fit Details</label>
                <input
                  type="text"
                  className={formStyles.formInput}
                  value={sizeFit}
                  onChange={e => setSizeFit(e.target.value)}
                  placeholder="e.g. Tailored slim-fit silhouette."
                  id="field-sizefit"
                />
              </div>
            </div>

            {/* ======================================================= */}
            {/* CREATE PRODUCT / SAVE CHANGES ACTION (BOTTOM)           */}
            {/* ======================================================= */}
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.75rem', marginTop: '1.5rem', borderTop: '1px solid #e4e4e7', paddingTop: '1.25rem' }}>
              <button
                type="button"
                className={formStyles.secondaryBtn}
                onClick={() => { setIsEditing(false); setEditingId(null); }}
              >
                Cancel
              </button>
              <button
                type="submit"
                className={formStyles.primaryYellowBtn}
                disabled={loading || isUploadingImages || Boolean(isCurrentDuplicate)}
                title={isCurrentDuplicate ? 'Cannot save duplicate product configuration' : undefined}
                id="btn-save-bottom"
              >
                <Save size={16} />
                <span>{loading ? 'Saving...' : editingId ? 'Save Changes' : 'Create Product'}</span>
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
}
